services:
  db:
    image: postgres:16
    container_name: routine_db
    environment:
      POSTGRES_USER: routine
      POSTGRES_PASSWORD: routine_password
      POSTGRES_DB: routine
    ports:
      - "5432:5432"
    volumes:
      - routine_db_data:/var/lib/postgresql/data

volumes:
  routine_db_data: